# This module defines the macro compute_platform_str

cmake_minimum_required(VERSION 2.8.7)

macro(compute_platform_str varname)
    if(MSVC)
        math(EXPR msvc_normalized_version "(${MSVC_VERSION} - 600) / 10" )
        if( ${CMAKE_SIZEOF_VOID_P} EQUAL 4 )
            set(${varname} vc${msvc_normalized_version})
        else()
            set(${varname} vc${msvc_normalized_version}_x64)
        endif()
    elseif(APPLE)
        if(IOS)
            set(${varname} ios_${CMAKE_CXX_COMPILER_ID}${CMAKE_CXX_COMPILER_VERSION})
        else()
            set(${varname} mac_${CMAKE_CXX_COMPILER_ID}${CMAKE_CXX_COMPILER_VERSION})
        endif()
        string(TOLOWER "${${varname}}" ${varname})
        string(REPLACE "." "_" ${varname} "${${varname}}")
    elseif(UNIX)
        set(${varname} linux)
    endif()
    message("Detected platform: ${${varname}}")
endmacro()